#!/bin/bash

echo -e "\033[31;4mEnter Ipv6\033[0m";read ipv6

echo -e "\033[31;4mEndPoint\033[0m";read endpoint

echo -e "\033[31;4mipv4 address:\033[0m";read ipv4

echo -e "\033[31;4minterfaces tour (eth0,ech1,ens3.....)\033[0m";read ipvtur

echo -e "\033[31;4mDelete and type the last 2 digits of your Ipv4 address (Linode version Special)\033[0m";read ipv4452

cat > /etc/network/interfaces << END
# Generated by Linode Network Helper
# Thu Jun 18 09:18:51 2020 UTC
#
# This file is automatically generated on each boot with your Linode's
# current network configuration. If you need to modify this file, please
# first disable the 'Auto-configure Networking' setting within your Linode's
# configuration profile:
#  - https://manager.linode.com/linodes/config/ubuntu-eu-central-001?id=22502123
#
# For more information on Network Helper:
#  - https://www.linode.com/docs/platform/network-helper
#
# A backup of the previous config is at /etc/network/.interfaces.linode-last
# A backup of the original config is at /etc/network/.interfaces.linode-orig
#
# /etc/network/interfaces

# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# This is an autoconfigured IPv6 interface
iface $ipvtur inet6 auto

# The primary network interface
auto $ipvtur
iface $ipvtur inet static
    address $ipv4/24
    gateway $ipv4452
	
auto he-ipv6
iface he-ipv6 inet6 v4tunnel
        address $ipv6::2
        netmask 64
        endpoint $endpoint
        local $ipv4
        ttl 255
        gateway $ipv6::1
END
